name: Profile

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sync profile
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
        run: echo "${{ secrets.PROFILE }}" | base64 -d | bash
